image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build **/*.csproj"

test:
    stage: test
    script: 
        - "dotnet test **/*[Ttests]/*.csproj"