image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build src/KP.BackEnd.sln"

test:
    stage: test
    script: 
        - "dotnet test src/KP.BackEnd.Tests/KP.BackEnd.Tests.csproj"